# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-08 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemToBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(choices=[(b'Dairy', b'Dairy'), (b'Bread', b'Bread'), (b'Meat', b'Meat'), (b'Vegetable', b'Vegetable'), (b'Beverage', b'Beverage')])),
                ('name', models.TextField()),
                ('important', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
